### ISSUE TITLE
Hide overflowing tabs in a menu

### ISSUE THREAD

**Issue by skttl** [skttl/our-umbraco-matryoshka#12]
Should I hide overflowing tabs in a menu, like v7 did?
![image](https://user-images.githubusercontent.com/3726467/77639976-e603c280-6f59-11ea-9031-eb8d8df0fc18.png)

**Comment by robertjf** [comment]
I vote yes - a little drop down to the right of the visible tabs, or even be able to scroll the tabs side-to-side perhaps

**Comment by skttl** [comment]
Fixed by https://github.com/skttl/our-umbraco-matryoshka/commit/5471f4e1f3cc80bb69e7f59c7024ef5496bb68bd
