### ISSUE TITLE
Matryoshka removing min/max validation on multinode pickers

### ISSUE THREAD

**Issue by TheMirzai** [skttl/our-umbraco-matryoshka#13]
My usecase on this is having a multinode picker where you have to pick a minimum of 4 item, and a maximum of 5. When saving with 3 items, no validation is thrown with Matryoshka installed.

I've dug into Umbraco and within the valPropertyMsg in umbraco.directives.js, the errors look to be empty when hitting "Save and Publish" for some reason. Not sure if anything is getting wiped at any point.

Reproduction
------------

- Fresh VS 2019 (Empty) project, standard install of Umbraco 8.6.0
- Create Custom Multinode picker with minimum 4, maximum 5. Attempt to add 3 nodes and when hitting "Save and Publish", validation error message is thrown.
- Installed Matryoshka 0.1.0
- Redo above step, hit "Save and Publish" and item is saved successfully.

**Comment by skttl** [comment]
Fixed in https://github.com/skttl/our-umbraco-matryoshka/commit/87a9032b3fc21a0afd9659601cba97475ba1b1c5
