### ISSUE TITLE
Editing document type hides tabs as if they're overflowing

### ISSUE THREAD

**Issue by stefankip** [skttl/our-umbraco-matryoshka#15]
Steps to reproduce:
- Open a content item
- Open the document type via the Info app
- Save and close the document type
- Open the Content app again
Now the tabs are hidden as if they're overflowing.

**Comment by FransdeJong** [comment]
If you resize the screen by only one pixel it resolves itself.
So maybe we could call the calculateWidth() function every time you open the Content tab this would be fixed right?

**Comment by skttl** [comment]
It does the same whenever you open an infinite editor, ie. when editing DTGEs.

**Comment by FransdeJong** [comment]
I don't experience the same behaviour with DTGE or another infinite editor.
Even if I go to edit the doctype and hit close instead of submit it doesn't behave like this.

It only callapses when I edit the doctype and hit submit

**Comment by skttl** [comment]
a5d61b4 changes the logic from using window resize events to using a ResizeObserver. ResizeObserver is currently behind a flag in Safari (I guess Safari 14 which should be due anytime soon will have it), else its supported in all modern browsers.

**Comment by stefankip** [comment]
Correct link: https://github.com/skttl/our-umbraco-matryoshka/commit/a5d61d425380e12c8419616b3df2162fa4d8c66c
