### ISSUE TITLE
Nothing happens when I click on the dropdown buttons

### ISSUE THREAD

**Issue by stefankip** [skttl/our-umbraco-matryoshka#23]
In #19 the feature was added to scroll to groups inside a tab with dropdown buttons.
I just updated to 0.3.0 via NuGet and I can see the dropdown. But clicking on the buttons doesn't scroll to the group.
Instead, if I scroll down a little bit and click on one of the dropdowns, the page just scrolls to the top.

**Comment by skttl** [comment]
Did you update the client dependency version?

**Comment by stefankip** [comment]
No, I thought that manually updating the CD version was something of the past though? :-p

**Comment by skttl** [comment]
It isn't for this package :)

**Comment by stefankip** [comment]
I tried it just now and still doesnt't work though.

**Comment by MiguelLopez6** [comment]
It seems the groups are missing the id. I fixed this and another issue on a pull request: Scroll to groups #24

**Comment by kipusoep** [comment]
Nice job @MiguelLopez6! 🥳
