### ISSUE TITLE
Align layout in dialogs (DTGE)

### ISSUE THREAD

**Issue by skttl** [skttl/our-umbraco-matryoshka#4]
![image](https://user-images.githubusercontent.com/3726467/73883532-68c6a600-4864-11ea-8a38-a5ba887c41c9.png)
This is how Matryoshka looks when used in eg. DTGE. The one with the arrow is a Matryoshka Group Separator.

Should I use tabs here? Comments welcome.

Also a slight variation in looks between "real" Umbraco groups and Matryoshka groups, that should be aligned.

**Comment by deanleigh** [comment]
We have just installed Matryoshka and are so happy to have tabs back. It would be great to have them back in DTGE as well.

**Comment by skttl** [comment]
This would probably require a new package (Matryoshka for DTGEs), as DTGE has its own view, that would need to be replaced.

**Comment by deanleigh** [comment]
Let's see how the new block editor progresses.

**Comment by skttl** [comment]
Closing this, as this is out of scope for this package - would require another package.

**Comment by skttl** [comment]
Well, you live, and you learn...

DTGE support is added in 9ef759b
