### ISSUE TITLE
Looks broken in Nested Content

### ISSUE THREAD

**Issue by skttl** [skttl/our-umbraco-matryoshka#5]
![image](https://user-images.githubusercontent.com/3726467/73883719-ba6f3080-4864-11ea-87b6-83ab27060cba.png)

Open for suggestions on how it should look in Nested Content.

**Comment by AndersBrohus-MySupport** [comment]
Just to understand this is when you use the Matryoshka Group Separator in an Nested Content or? :)

**Comment by skttl** [comment]
Yes :)

**Comment by FransdeJong** [comment]
IMO there are two possible solutions:

What is your prefered solution? Show a styled separator? Or don't show the separator at all in nested content?

**Comment by skttl** [comment]
I think a styled seperator probably would be nice.

**Comment by EcreoApS** [comment]
How about this? Very subtle...

![image](https://user-images.githubusercontent.com/63776873/80318860-562d8e80-880d-11ea-8cf8-b696bcccce15.png)

**Comment by skttl** [comment]
How about this? Very subtle...

![image](https://user-images.githubusercontent.com/3726467/80318893-8b39e100-880d-11ea-9f11-9da3c0ff4f60.png)

Could probably work great with collapsible groups (#3)

**Comment by skttl** [comment]
Fixed in https://github.com/skttl/our-umbraco-matryoshka/commit/6b2610c738f96fad371297f31def609985364778
