### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by erikjanwestendorp** [skttl/our-umbraco-matryoshka#6]
Just wondering, are there any plans to create a NuGet package? 👍

**Comment by skttl** [comment]
There is :)

I haven't had the time yet, but maybe you or someone else could do it?

**Comment by erikjanwestendorp** [comment]
@skttl Awesome! If I have some time I'll have a look :-)

**Comment by stefankip** [comment]
And did you have a look @erikjanwestendorp?

**Comment by erikjanwestendorp** [comment]
@stefankip No I am not working on it yet.

**Comment by stefankip** [comment]
Nice work @skttl 👍
