### ISSUE TITLE
Cannot insert media in rich text editor

### ISSUE THREAD

**Issue by sajphon** [skttl/our-umbraco-matryoshka#7]
After installing matryoshka (tested with / without the plugin) I am not able to pick media item to insert it into Rich text editor.

![image](https://user-images.githubusercontent.com/1340069/75502779-1f392900-59d4-11ea-87d1-5f57dd9e0965.png)

**Comment by BartoTato** [comment]
Hi

Did you sort it out? I have the same issue.

**Comment by skttl** [comment]
A workaround is posted here
https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/101467-select-image-disasbled

Apparently the same bug appears in DTGE...

**Comment by BartoTato** [comment]
Hi, I tried that but it doesn't seem to work ( on version 8.5.3 and 8.5.5).

**Comment by T9Creative** [comment]
I had the same issue as well, and trying the suggested workaround did not work. Was only able to add media after uninstalling and making sure was deleted from App_Plugins the Matryoshka plugin.

**Comment by sajphon** [comment]
I did it manually in the end. Without the use of rich text editor.

**Comment by BartoTato** [comment]
Thanks for your reply. We had to uninstall at the end as it was by far too time-consuming to "debug" and client was dependant on multiple media uploads.

**Comment by skttl** [comment]
Fixed in https://github.com/skttl/our-umbraco-matryoshka/commit/25aff5b01a6df758668d6c7758022a3b8d5fa523
