### ISSUE TITLE
Nested Contents add content dialog is behind the header on small screens with many document elements

### ISSUE THREAD

**Issue by webtimisten** [skttl/our-umbraco-matryoshka#9]
Hello Søren

There is a bit of a problem in your CSS causing the Nested Content getting behind stuff.

Look at this issue:
https://github.com/umbraco/Umbraco-CMS/issues/7519

It's because of this in your CSS:
`.umb-editor-container { z-index:2; }`

**Comment by skttl** [comment]
Fixed in 25aff5b
